### ISSUE TITLE
all settings are lost on relaunch

### ISSUE THREAD

**Issue by tipu** [flathub/com.tdameritrade.ThinkOrSwim#9]
every time i relaunch thinkorswim, i have to switch account type from schwabb to tdameritrade, login, all my watchlists setup (not the lists themselves, but how they're laid out). how can i get these settings to persist between launches?

**Comment by jkoelker** [comment]
The problem is the documented (or undocumented however you view it), `-dir` option to the installer is not honored anymore and it always installs to `$HOME/thinkorswim`. It appears that this is somewhere in the extracted binary itself as a test install specifying `./t` as the target dir the log says:

```
Variable changed: allInstallationDir=/home/jkoelker/Downloads/t[class java.io.File]
Variable changed: myInstallationDir=/home/jkoelker/thinkorswim[class java.io.File]
```

And then it proceeds later to just use the value of `myInstallationDir`. So every launch its actually a new install now. Not sure when this changed but it *used* to not be the case.

Given the comments from https://www.reddit.com/r/thinkorswim/comments/1axrcjm/charles_schwab_will_not_support_any_future/, I'm not sure if you report the bug to them or not will result in them fixing it, and I don't have a windows or mac device to repro on it there, although I suspect that they both have the same issue.

You might try exposing all of `/home` to the app via `flatseal`. If that works, I'd be happy to merge a PR if sent in.

**Comment by jkoelker** [comment]
I believe that with https://github.com/flathub/com.tdameritrade.ThinkOrSwim/pull/10 it will now preserve again. Please try it out and let me know if it works.
